name: Deploy Bicep Template

on:
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.SERVICE_PRINCIPLE_CREDENTIALS }}

    - name: Install Bicep CLI
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep
        bicep --help

    - name: Compile Bicep to ARM
      run: |
        working_directory=$GITHUB_WORKSPACE
        bicep build ${working_directory}/InfrastructureAsCode/main.bicep environment=prod

    - name: Deploy ARM template
      uses: azure/arm-deploy@v1
      with:

        scope: resourcegroup
        resourceGroupName: ${{ vars.WTH_RESOURCE_GROUP}}
        template: '${{ github.workspace }}/InfrastructureAsCode/main.json'