# create a github action workflow with two steps within it. The steps should be simple CLI commands to echo out step1 and step2 as applicable.
name: github-workflow-1

on: 
    workflow_dispatch:
    issues:
      types: [opened]

env:
    REPO_SECRET: ${{ secrets.FIRST_SECRET }}

jobs:
    job1:
        runs-on: ubuntu-latest

        steps:
        - name: Step 1
          run: echo "$REPO_SECRET"

        - name: Step 2
          run: echo "This is Step 2"

    job2:
        needs: job1
        runs-on: ubuntu-latest

        steps:
        - name: Cowsay Step
          uses: mscoutermarsh/cowsays-action@master
          with:
            text: 'ship ship ship!'
            color: 'red'