name: WTH Team 8 First Workflow

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Job-1-What-The-Hack-Team8:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Step 1."
      - run: echo "🎉 Step 2."

  Job-2-cowsays:
    name: This job is Cowsays
    runs-on: ubuntu-latest
    steps:
    - name: Ship it
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'What the Hack!'
        color: 'yellow'
